### ISSUE TITLE
hacked pt.2

### ISSUE THREAD

**Issue by jyliuuu** [dmuller021/noid-cord#3]
01001100 01101111 01110010 01100101 01101101 00100000 01101001 01110000 01110011 01110101 01101101 00100000 01100100 01101111 01101100 01101111 01110010 00100000 01110011 01101001 01110100 00100000 01100001 01101101 01100101 01110100 00101100 00100000 01100011 01101111 01101110 01110011 01100101 01100011 01110100 01100101 01110100 01110101 01110010 00100000 01100001 01100100 01101001 01110000 01101001 01110011 01100011 01101001 01101110 01100111 00100000 01100101 01101100 01101001 01110100 00101110 00100000 01010000 01101000 01100001 01110011 01100101 01101100 01101100 01110101 01110011 00100000 01101100 01100001 01100011 01101001 01101110 01101001 01100001 00100000 01100001 01100011 00100000 01100101 01110010 01100001 01110100 00100000 01110101 01110100 00100000 01101000 01100101 01101110 01100100 01110010 01100101 01110010 01101001 01110100 00101110 00100000 01010110 01101001 01110110 01100001 01101101 01110101 01110011 00100000 01110000 01110010 01100101 01110100 01101001 01110101 01101101 00101100 00100000 01101101 01100101 01110100 01110101 01110011 00100000 01110001 01110101 01101001 01110011 00100000 01110000 01101111 01110011 01110101 01100101 01110010 01100101 00100000 01110110 01110101 01101100 01110000 01110101 01110100 01100001 01110100 01100101 00101100 00100000 01110011 01100101 01101101 00100000 01110011 01100101 01101101 00100000 01101100 01110101 01100011 01110100 01110101 01110011 00100000 01110001 01110101 01100001 01101101 00101100 00100000 01110110 01100101 01101110 01100101 01101110 01100001 01110100 01101001 01110011 00100000 01101101 01100001 01110100 01110100 01101001 01110011 00100000 01100101 01110011 01110100 00100000 01100001 01110010 01100011 01110101 00100000 01100101 01110100 00100000 01101100 01100001 01100011 01110101 01110011 00101110 00100000 01000011 01101100 01100001 01110011 01110011 00100000 01100001 01110000 01110100 01100101 01101110 01110100 00100000 01110100 01100001 01100011 01101001 01110100 01101001 00100000 01110011 01101111 01100011 01101001 01101111 01110011 01110001 01110101 00100000 01100001 01100100 00100000 01101100 01101001 01110100 01101111 01110010 01100001 00100000 01110100 01101111 01110010 01110001 01110101 01100101 01101110 01110100 00100000 01110000 01100101 01110010 00100000 01100011 01101111 01101110 01110101 01100010 01101001 01100001 00100000 01101110 01101111 01110011 01110100 01110010 01100001 00101100 00100000 01110000 01100101 01110010 00100000 01101001 01101110 01100011 01100101 01110000 01110100 01101111 01110011 00100000 01101000 01101001 01101101 01100101 01101110 01100001 01100101 01101111 01110011 00101110 00100000 01000001 01101100 01101001 01110001 01110101 01100001 01101101 00100000 01110100 01100101 01101101 01110000 01101111 01110010 00100000 01110011 01100101 01101101 00100000 01100101 01110010 01100001 01110100 00101100 00100000 01110011 01101001 01110100 00100000 01100001 01101101 01100101 01110100 00100000 01110110 01100101 01101000 01101001 01100011 01110101 01101100 01100001 00100000 01110011 01100101 01101101 00100000 01101000 01100101 01101110 01100100 01110010 01100101 01110010 01101001 01110100 00100000 01101101 01101111 01101100 01100101 01110011 01110100 01101001 01100101 00101110 00100000 01010011 01100101 01100100 00100000 01110000 01100101 01101100 01101100 01100101 01101110 01110100 01100101 01110011 01110001 01110101 01100101 00100000 01100100 01101001 01100011 01110100 01110101 01101101 00100000 01101001 01110000 01110011 01110101 01101101 00100000 01100001 01110100 00100000 01110000 01110010 01100101 01110100 01101001 01110101 01101101 00101110 00100000 01001110 01110101 01101100 01101100 01100001 00100000 01101101 01100001 01100111 01101110 01100001 00100000 01110110 01100101 01101100 01101001 01110100 00101100 00100000 01110110 01101001 01110110 01100101 01110010 01110010 01100001 00100000 01101001 01100100 00100000 01110000 01101100 01100001 01100011 01100101 01110010 01100001 01110100 00100000 01110110 01100101 01101100 00101100 00100000 01110000 01110101 01101100 01110110 01101001 01101110 01100001 01110010 00100000 01101001 01101110 00100000 01101101 01100101 01110100 01110101 01110011 00101110 00100000 01001110 01110101 01101110 01100011 00100000 01101101 01100001 01111000 01101001 01101101 01110101 01110011 00100000 01100101 01100111 01100101 01110100 00100000 01101100 01100101 01100011 01110100 01110101 01110011 00100000 01101001 01101110 00100000 01100011 01101111 01101110 01110011 01100101 01110001 01110101 01100001 01110100 00101110 00100000 01000100 01101111 01101110 01100101 01100011 00100000 01110000 01101111 01110011 01110101 01100101 01110010 01100101 00100000 01110100 01110101 01110010 01110000 01101001 01110011 00100000 01101001 01101110 00100000 01110110 01100101 01101000 01101001 01100011 01110101 01101100 01100001 00100000 01110101 01101100 01101100 01100001 01101101 01100011 01101111 01110010 01110000 01100101 01110010 00101110 00100000 01000011 01110101 01110010 01100001 01100010 01101001 01110100 01110101 01110010 00100000 01100001 01100011 01100011 01110101 01101101 01110011 01100001 01101110 00100000 01101010 01110101 01110011 01110100 01101111 00100000 01101100 01100001 01100011 01110101 01110011 00101100 00100000 01100001 01110100 00100000 01100011 01101111 01101110 01110110 01100001 01101100 01101100 01101001 01110011 00100000 01100001 01110010 01100011 01110101 00100000 01100101 01101100 01100101 01101101 01100101 01101110 01110100 01110101 01101101 00100000 01110011 01100101 01100100 00101110 00100000 01010110 01101001 01110110 01100001 01101101 01110101 01110011 00100000 01100011 01101111 01101110 01100111 01110101 01100101 00100000 01110101 01101100 01110100 01110010 01101001 01100011 01101001 01100101 01110011 00100000 01100101 01101100 01101001 01110100 00101100 00100000 01110110 01100101 01101100 00100000 01100011 01101111 01101101 01101101 01101111 01100100 01101111 00100000 01101110 01110101 01101100 01101100 01100001 00100000 01100011 01101111 01101110 01110011 01100101 01100011 01110100 01100101 01110100 01110101 01110010 00100000 01101001 01101110 00101110 00100000 01000001 01101100 01101001 01110001 01110101 01100001 01101101 00100000 01100101 01110100 00100000 01100001 01101100 01101001 01110001 01110101 01100101 01110100 00100000 01101110 01110101 01101100 01101100 01100001 00101110 00100000 01010011 01100101 01100100 00100000 01101101 01101111 01101100 01100101 01110011 01110100 01101001 01100101 00100000 01101100 01100001 01101111 01110010 01100101 01100101 01110100 00100000 01110011 01100001 01110000 01101001 01100101 01101110 00100000 01110011 01100101 01100100 00100000 01110101 01101100 01110100 01110010 01101001 01100011 01100101 01110011 00101110 00100000 01001110 01100001 01101101 00100000 01101100 01101111 01110010 01100101 01101101 00100000 01100110 01100101 01101100 01101001 01110011 00101100 00100000 01110100 01101001 01101110 01100011 01101001 01100100 01110101 01101110 01110100 00100000 01110011 01100101 01100100 00100000 01101010 01110101 01110011 01110100 01101111 00100000 01110110 01101001 01110100 01100001 01100101 00101100 00100000 01110000 01101111 01110010 01110100 01110100 01101001 01110100 01101111 01110010 00100000 01100110 01100101 01110010 01101101 01100101 01101110 01110100 01110101 01101101 00100000 01100001 01101110 01110100 01100101 00101110 00100000 01000100 01101111 01101110 01100101 01100011 00100000 01100110 01110010 01101001 01101110 01100111 01101001 01101100 01101100 01100001 00100000 01100011 01101111 01101110 01110011 01100101 01100011 01110100 01100101 01110100 01110101 01110010 00100000 01110100 01100101 01101100 01101100 01110101 01110011 00100000 01100001 00100000 01100110 01100001 01100011 01101001 01101100 01101001 01110011 01101001 01110011 00101110

**Comment by dmuller021** [comment]
KUSO

**Comment by jyliuuu** [comment]
![IMG_4352](https://user-images.githubusercontent.com/95280727/148553910-5364b179-c0b2-465e-a506-8dd251308a78.png)

**Comment by dmuller021** [comment]
01100010 01110010 01101111 00100000 01101000 01101111 01100101 01111010 01101111 00100000 01110011 01110100 01110101 01110101 01110010 00100000 01101010 01100101 00100000 01101110 01101111 01110101 00100000 01101100 01101111 01110010 01100101 01101101 00100000 01101001 01110000 01110011 01110101 01101101 00100000 01100010 01101001 01101110 01100001 01110010 01111001 00100000 01101110 01110101 01101101 01100010 01100101 01110010 01110011

**Comment by jyliuuu** [comment]
future car????????
![IMG_4352](https://user-images.githubusercontent.com/95280727/148554227-5867f91d-8352-493f-8fd1-b517e3004bf1.png)

**Comment by jyliuuu** [comment]
![EH2QuUIWwAAI_He](https://user-images.githubusercontent.com/95280727/148554276-744d1c67-6f4d-48fe-8e46-f01ac72cdaa8.png)

**Comment by dmuller021** [comment]
bro heb je mercedes benz vision EQX gezien!?  


![Uploading mercedes-vision-eqxx-concept-actieradius-1000-km-5.jpg…]()

**Comment by jyliuuu** [comment]
ja kaulo sexy
